In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('seattle-weather.csv')

In [32]:
dataset = dataset.drop(columns=['date'])

In [33]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [34]:
print(x)

[[ 0.  12.8  5.   4.7]
 [10.9 10.6  2.8  4.5]
 [ 0.8 11.7  7.2  2.3]
 ...
 [ 0.   7.2  0.6  2.6]
 [ 0.   5.6 -1.   3.4]
 [ 0.   5.6 -2.1  3.5]]


In [35]:
print(y)

['drizzle' 'rain' 'rain' ... 'fog' 'sun' 'sun']


In [36]:
dataset.describe()

precipitation     temp_max     temp_min         wind
count    1461.000000  1461.000000  1461.000000  1461.000000
mean        3.029432    16.439083     8.234771     3.241136
std         6.680194     7.349758     5.023004     1.437825
min         0.000000    -1.600000    -7.100000     0.400000
25%         0.000000    10.600000     4.400000     2.200000
50%         0.000000    15.600000     8.300000     3.000000
75%         2.800000    22.200000    12.200000     4.000000
max        55.900000    35.600000    18.300000     9.500000

In [37]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 0:4])
x[:, 0:4] = imputer.transform(x[:, 0:4])

In [38]:
print(x)

[[ 0.  12.8  5.   4.7]
 [10.9 10.6  2.8  4.5]
 [ 0.8 11.7  7.2  2.3]
 ...
 [ 0.   7.2  0.6  2.6]
 [ 0.   5.6 -1.   3.4]
 [ 0.   5.6 -2.1  3.5]]


In [39]:
print(y)

['drizzle' 'rain' 'rain' ... 'fog' 'sun' 'sun']


In [40]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [41]:
print(y)

[0 2 2 ... 1 4 4]


In [43]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)
print(x_train)

[[ 0.5 23.3 15.6  2.6]
 [ 2.8 16.1 11.1  4.5]
 [ 0.  26.7 14.4  3.1]
 ...
 [ 0.   5.6 -3.2  1.2]
 [ 0.  21.1 13.9  3.8]
 [ 3.3 14.4 11.7  6.6]]


In [44]:
print(x_test)

[[ 0.  18.3 10.   2.6]
 [ 0.  19.4 10.   2.6]
 [ 0.   7.8  3.9  1.9]
 ...
 [17.3 10.   4.4  3.4]
 [ 2.  17.2 15.   2. ]
 [ 0.  21.1  7.2  4.1]]


In [45]:
print(y_test)

[0 4 2 4 2 2 1 2 2 2 4 1 4 4 2 4 4 4 4 1 2 4 4 2 2 1 4 2 2 4 4 2 1 2 4 4 4
 4 2 0 4 4 4 2 2 2 2 4 2 2 4 4 2 2 4 2 4 2 4 4 4 4 2 2 2 2 2 4 4 4 2 4 4 2
 4 2 3 2 2 4 1 4 2 2 4 2 4 4 1 2 4 4 4 4 2 4 4 4 2 4 4 4 1 3 2 0 4 2 4 4 4
 2 4 2 4 4 4 2 4 2 1 2 2 4 4 2 2 1 2 4 2 2 4 2 4 1 2 4 0 4 2 1 2 4 2 2 1 4
 2 2 2 2 2 4 1 4 4 4 2 4 2 4 2 4 2 4 4 4 1 4 1 2 1 2 2 2 1 2 0 2 2 4 1 2 1
 2 1 4 4 2 3 3 0 2 1 4 0 3 2 2 4 4 2 2 4 4 4 4 0 2 4 2 2 2 1 4 2 2 4 2 1 2
 2 2 4 1 2 4 2 4 2 2 2 4 4 2 4 2 2 2 2 0 2 4 1 2 2 4 4 4 4 4 4 2 4 1 2 2 0
 0 4 2 4 4 4 2 4 2 2 4 4 2 2 1 2 4 4 2 2 4 2 2 2 2 4 2 1 2 3 2 2 2 4]


In [46]:
print(y_train)

[2 2 4 ... 4 4 2]


In [48]:
print(x_train.shape)

(1168, 4)


In [49]:
print(x_test.shape)

(293, 4)


In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, :4] = sc.fit_transform(x_train[:, :4])
x_test[:, :4] = sc.transform(x_test[:, :4])

In [53]:
print(x_train)

[[-0.37618839  0.92375526  1.45212016 -0.45465358]
 [-0.03472586 -0.04557571  0.56411174  0.87661338]
 [-0.45041937  1.38149488  1.21531792 -0.10432017]
 ...
 [-0.45041937 -1.45918337 -2.25778168 -1.43558714]
 [-0.45041937  0.6275708   1.11665032  0.3861466 ]
 [ 0.03950512 -0.27444552  0.68251287  2.34801371]]


In [54]:
print(x_test)

[[-0.45041937  0.25060876  0.34704302 -0.45465358]
 [-0.45041937  0.39870099  0.34704302 -0.45465358]
 [-0.45041937 -1.1629989  -0.85670173 -0.94512036]
 ...
 [ 2.11797266 -0.86681444 -0.75803413  0.10587988]
 [-0.15349544  0.10251652  1.33371904 -0.87505368]
 [-0.45041937  0.6275708  -0.20549556  0.59634665]]
